# app/ruff.toml

[lint]
# RUF012 wants us to use typing.ClassVar for class variables like 'fields' or 'serializer_class'.
# In Django and DRF, it is standard not to use ClassVar, so we disable this rule.
# BLE001 complains about 'except Exception:', but in our async tasks we want to catch EVERYTHING.
ignore = ["RUF012", "BLE001"]